
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 14 12:30:38 CET 2025
//----------------------------------------------------

package mini_java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAST = 40;
  public static final int LBRA = 27;
  public static final int UMINUS = 38;
  public static final int INT = 12;
  public static final int FOR = 9;
  public static final int MINUS = 34;
  public static final int LSQ = 25;
  public static final int CMP = 4;
  public static final int CST = 3;
  public static final int INSTANCEOF = 11;
  public static final int STATIC = 17;
  public static final int NOT = 22;
  public static final int SEMICOLON = 31;
  public static final int AND = 20;
  public static final int LP = 23;
  public static final int OR = 21;
  public static final int COMMA = 29;
  public static final int CLASS = 6;
  public static final int DIV = 36;
  public static final int RP = 24;
  public static final int PLUS = 33;
  public static final int IF = 10;
  public static final int THIS = 18;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 16;
  public static final int EQUAL = 30;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int RSQ = 26;
  public static final int NULL = 14;
  public static final int RBRA = 28;
  public static final int MOD = 37;
  public static final int IDENT = 2;
  public static final int VOID = 19;
  public static final int TIMES = 35;
  public static final int ELSE = 7;
  public static final int PUBLIC = 15;
  public static final int THEN = 39;
  public static final int EXTENDS = 8;
  public static final int PAREN = 41;
}

